### ISSUE TITLE
Arm64 not published on the APT repository

### ISSUE THREAD

**Issue by cyber-anon** [signmykeyio/signmykey#160]
Following the installation instructions for ARM64, I run into this problem:

N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://apt.signmykey.io stable InRelease' doesn't support architecture 'arm64'
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package signmykey

**Comment by pablo-ruth** [comment]
Hello @cyber-anon, I just release v0.8.1 with arm64 for linux on the APT repository, can you check that it's ok for you ?

**Comment by cyber-anon** [comment]
Hi
it doesn't work, probably because it's in the wrong folder?
It should be here, I guess:
https://signmykey.jfrog.io/ui/native/signmykey-deb/dists/stable/main/
It is here:
https://signmykey.jfrog.io/ui/native/signmykey-deb/

But I'm not familiar with apt repositories, so I may be wrong. 
The error message I get in the system (obviously, after running apt update) is:

N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://apt.signmykey.io stable InRelease' doesn't support architecture 'arm64'

And indeed, the file https://signmykey.jfrog.io/artifactory/signmykey-deb/dists/stable/InRelease has only 2 architectures: amd64 and i386

**Comment by pablo-ruth** [comment]
Ok I fixed the upload path, can you retry ?

**Comment by cyber-anon** [comment]
Yes, I checked and it works
Thanks
