### ISSUE TITLE
Keycloak: no more working with Keycloak 23.0.6

### ISSUE THREAD

**Issue by Leopol123** [signmykeyio/signmykey#211]
Hello,

We are working with Signmykey for years using Keycloak for auth and vault for signing SSH key. It was working like a charm. I am migrating Keycloak to 23.0.6, exporting/importing "Keycloak clients" including "signmykey" client. And Signmykey no working anymore...

It seems there is an issue when Signmykey tries to get list of principals for my user:

Keycloak 23.0.6 (using Quarkus)
`{"ctx":"api","error":"unexpected end of JSON input","handler":"sign","level":"error","msg":"Getting list of user principals","req_id":"signmykey-785c7cf4cd-4q7tj/oqgurNDsH1-000001","user":"oidc-my-user"} `

When I roll back to old Keycloak, I have this logs :
Keycloak 17.0.0 (using Wildfly)
`{"ctx":"api","handler":"sign","level":"info","msg":"User principals retrieved","principals":["MYGROUP1","MYGROUP2"],"req_id":"signmykey-785c7cf4cd-f2pmw/ChOwIytdnP-000003","user":"oidc-my-user"}`

Do you have any idea to solve this issue ? I can do some tests if needed. Thanks for your help !

**Comment by pablo-ruth** [comment]
Hey @Leopol123,

Thanks for pointing out that issue. I took a look and realized the token request from Signmykey to Keycloak was missing the "openid" scope – something that's needed after a recent change in Keycloak (more about that here: https://github.com/keycloak/keycloak/pull/14237). I've patched it up in this PR: https://github.com/signmykeyio/signmykey/pull/212.

Would you mind giving the latest release (https://github.com/signmykeyio/signmykey/releases/tag/v0.8.6) a spin to see if it sorts things out for you?

**Comment by Leopol123** [comment]
Hello @pablo-ruth,

I do the same test using the new release, it's working ! Thanks !
