### ISSUE TITLE
problem with the extention permit-x11-forwarding

### ISSUE THREAD

**Issue by cyber-anon** [signmykeyio/signmykey#230]
Using viper to read the config file, creates a problem with the SSH certificate extension "permit-X11-forwarding" which is converted to lowercase "permit-x11-forwarding" and thus is invalid / unknown.

I do not know how this could be solved. 
This seems to be an inherent limitation of viper older than 5 years, and the most common solution people are implementing, is to migrate to another package. 

https://github.com/spf13/viper/issues/1014

Since the only case-sensitive extension is this, maybe a solution would be to iterate the Extensions map after being created, and if permit-x11-forwarding is found, modify it with the correct capitalization

**Comment by pablo-ruth** [comment]
Hi @cyber-anon, sorry for the delay. It's not the most elegant solution, but checking this edge case and fixing it is the simplest way. I've merged the fix and released it here: https://github.com/signmykeyio/signmykey/releases/tag/v0.8.7
